version: "3.7"

services:
    serve:
        # image: docker.pkg.github.com/eveisesi/zrule/zrule-api:0.3.2
        image: zrule:latest
        env_file: .env
        command: ./zrule serve
        container_name: serve
        hostname: serve
        network_mode: "host"
        ports:
            - 50200:3000
    dispatcher:
        # image: docker.pkg.github.com/eveisesi/zrule/zrule-api:0.3.2
        image: zrule:latest
        env_file: .env
        command: ./zrule dispatcher
        container_name: dispatcher
        hostname: dispatcher
        network_mode: "host"
    listener:
        # image: docker.pkg.github.com/eveisesi/zrule/zrule-api:0.3.2
        image: zrule:latest
        env_file: .env
        command: ./zrule listener
        container_name: listener
        hostname: listener
        network_mode: "host"
    processor:
        # image: docker.pkg.github.com/eveisesi/zrule/zrule-api:0.3.2
        image: zrule:latest
        env_file: .env
        command: ./zrule processor
        container_name: processor
        hostname: processor
        network_mode: "host"