version: "3.7"

services:
    serve:
        image: ${IMAGE_URI}
        env_file: .env
        command: ./zrule serve
        container_name: serve
        hostname: serve
        network_mode: "host"
    dispatcher:
        image: ${IMAGE_URI}
        env_file: .env
        command: ./zrule dispatcher
        container_name: dispatcher
        hostname: dispatcher
        network_mode: "host"
    listener:
        image: ${IMAGE_URI}
        env_file: .env
        command: ./zrule listener
        container_name: listener
        hostname: listener
        network_mode: "host"
    processor:
        image: ${IMAGE_URI}
        env_file: .env
        command: ./zrule processor
        container_name: processor
        hostname: processor
        network_mode: "host"